envoy:
  cluster:
    connect_timeout_ms: 1000
    circuit_breaker:
      max_connections: 1024
      max_requests: 50000
      max_pending_requests: 50000
      max_retries: 50000
    outlier_detection:
      base_ejection_time_in_seconds: 30
      ejection_sweep_interval_in_seconds: 10
      consecutive_5xx: 10000
      consecutive_gateway_failure: 5
      enforcing_consecutive_5xx: 0
      enforcing_consecutive_gateway_failure: 100
      max_ejection_percent: 50
  vhost:
    retry:
      retry_on: "connect-failure"
      retry_predicate: "envoy.retry_host_predicates.previous_hosts"
      num_retries: 3
      host_selection_max_retry_attempts: 3
operator:
  refresh_interval_in_s: 10
  envoy_discovery_mapping: ## required config
    - envoy_id: "id1"
      upstream_endpoint_label: "label1=val1"
      namespace: "namespace1"
    - envoy_id: "id2"
      upstream_endpoint_label: "label2=val2"
      namespace: "namespace2"
  log:
    level: info
