---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeterrr
  labels:
    app: greeterrr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeterrr
  template:
    metadata:
      labels:
        app: greeterrr
    spec:
      containers:
      - name: greeterrr
        image: gojektech/grpc-greeter:latest
        args:
          - ./greeterrr
          - server
        env:
        - name: NODE_NAME
          value: greeterrr
        ports:
        - containerPort: 8443
---
kind: Service
apiVersion: v1
metadata:
  name: greeterrr
  labels:
    heritage: envoy-lb
  annotations:
    envoy-lb-operator.gojektech.k8s.io/service-domain: something.abc.com:8080
    envoy-lb-operator.gojektech.k8s.io/service-type: grpc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: greeterrr
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
